services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puaas-app
    restart: unless-stopped
    environment:
      - AUTORRUN_ENABLED=true
      - AUTORUN_LARAVEL_MIGRATION_SEEDER=true
    ports:
      - "9006:8080"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql_puaas

  mysql_puaas:
    image: mysql:latest
    container_name: puaas-mysql
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: